/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CanopyRouteImport } from './routes/canopy'
import { Route as ClimbNotesRouteImport } from './routes/climb-notes'
import { Route as CorporateRouteImport } from './routes/corporate'
import { Route as FieldGuideRouteImport } from './routes/field-guide'
import { Route as GnomahRouteImport } from './routes/gnomah'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LunaRouteImport } from './routes/luna'
import { Route as MethodRouteImport } from './routes/method'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProceduresRouteImport } from './routes/procedures'
import { Route as ServiceRouteImport } from './routes/service'
import { Route as StartRouteImport } from './routes/start'
import { Route as VoiceRouteImport } from './routes/voice'
import { Route as DocsOnboardingRouteImport } from './routes/docs/onboarding'
import { Route as LunaIndexRouteImport } from './routes/luna/index'
import { Route as LunaSlugRouteImport } from './routes/luna/$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiCanopyRefreshRouteImport } from './routes/api/canopy/refresh'
import { Route as DocsOnboardingSplatRouteImport } from './routes/docs/onboarding/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CanopyRoute = CanopyRouteImport.update({
  id: '/canopy',
  path: '/canopy',
  getParentRoute: () => rootRouteImport,
} as any)
const ClimbNotesRoute = ClimbNotesRouteImport.update({
  id: '/climb-notes',
  path: '/climb-notes',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateRoute = CorporateRouteImport.update({
  id: '/corporate',
  path: '/corporate',
  getParentRoute: () => rootRouteImport,
} as any)
const FieldGuideRoute = FieldGuideRouteImport.update({
  id: '/field-guide',
  path: '/field-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const GnomahRoute = GnomahRouteImport.update({
  id: '/gnomah',
  path: '/gnomah',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LunaRoute = LunaRouteImport.update({
  id: '/luna',
  path: '/luna',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodRoute = MethodRouteImport.update({
  id: '/method',
  path: '/method',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProceduresRoute = ProceduresRouteImport.update({
  id: '/procedures',
  path: '/procedures',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceRoute = ServiceRouteImport.update({
  id: '/service',
  path: '/service',
  getParentRoute: () => rootRouteImport,
} as any)
const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const VoiceRoute = VoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsOnboardingRoute = DocsOnboardingRouteImport.update({
  id: '/docs/onboarding',
  path: '/docs/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LunaIndexRoute = LunaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LunaRoute,
} as any)
const LunaSlugRoute = LunaSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LunaRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCanopyRefreshRoute = ApiCanopyRefreshRouteImport.update({
  id: '/api/canopy/refresh',
  path: '/api/canopy/refresh',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsOnboardingSplatRoute = DocsOnboardingSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => DocsOnboardingRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/canopy': typeof CanopyRoute
  '/climb-notes': typeof ClimbNotesRoute
  '/corporate': typeof CorporateRoute
  '/field-guide': typeof FieldGuideRoute
  '/gnomah': typeof GnomahRoute
  '/login': typeof LoginRoute
  '/luna': typeof LunaRouteWithChildren
  '/method': typeof MethodRoute
  '/policies': typeof PoliciesRoute
  '/privacy': typeof PrivacyRoute
  '/procedures': typeof ProceduresRoute
  '/service': typeof ServiceRoute
  '/start': typeof StartRoute
  '/voice': typeof VoiceRoute
  '/docs/onboarding': typeof DocsOnboardingRouteWithChildren
  '/luna/$slug': typeof LunaSlugRoute
  '/luna/': typeof LunaIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/canopy/refresh': typeof ApiCanopyRefreshRoute
  '/docs/onboarding/$': typeof DocsOnboardingSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/canopy': typeof CanopyRoute
  '/climb-notes': typeof ClimbNotesRoute
  '/corporate': typeof CorporateRoute
  '/field-guide': typeof FieldGuideRoute
  '/gnomah': typeof GnomahRoute
  '/login': typeof LoginRoute
  '/method': typeof MethodRoute
  '/policies': typeof PoliciesRoute
  '/privacy': typeof PrivacyRoute
  '/procedures': typeof ProceduresRoute
  '/service': typeof ServiceRoute
  '/start': typeof StartRoute
  '/voice': typeof VoiceRoute
  '/docs/onboarding': typeof DocsOnboardingRouteWithChildren
  '/luna/$slug': typeof LunaSlugRoute
  '/luna': typeof LunaIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/canopy/refresh': typeof ApiCanopyRefreshRoute
  '/docs/onboarding/$': typeof DocsOnboardingSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/canopy': typeof CanopyRoute
  '/climb-notes': typeof ClimbNotesRoute
  '/corporate': typeof CorporateRoute
  '/field-guide': typeof FieldGuideRoute
  '/gnomah': typeof GnomahRoute
  '/login': typeof LoginRoute
  '/luna': typeof LunaRouteWithChildren
  '/method': typeof MethodRoute
  '/policies': typeof PoliciesRoute
  '/privacy': typeof PrivacyRoute
  '/procedures': typeof ProceduresRoute
  '/service': typeof ServiceRoute
  '/start': typeof StartRoute
  '/voice': typeof VoiceRoute
  '/docs/onboarding': typeof DocsOnboardingRouteWithChildren
  '/luna/$slug': typeof LunaSlugRoute
  '/luna/': typeof LunaIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/canopy/refresh': typeof ApiCanopyRefreshRoute
  '/docs/onboarding/$': typeof DocsOnboardingSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/canopy'
    | '/climb-notes'
    | '/corporate'
    | '/field-guide'
    | '/gnomah'
    | '/login'
    | '/luna'
    | '/method'
    | '/policies'
    | '/privacy'
    | '/procedures'
    | '/service'
    | '/start'
    | '/voice'
    | '/docs/onboarding'
    | '/luna/$slug'
    | '/luna/'
    | '/api/auth/$'
    | '/api/canopy/refresh'
    | '/docs/onboarding/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/canopy'
    | '/climb-notes'
    | '/corporate'
    | '/field-guide'
    | '/gnomah'
    | '/login'
    | '/method'
    | '/policies'
    | '/privacy'
    | '/procedures'
    | '/service'
    | '/start'
    | '/voice'
    | '/docs/onboarding'
    | '/luna/$slug'
    | '/luna'
    | '/api/auth/$'
    | '/api/canopy/refresh'
    | '/docs/onboarding/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/canopy'
    | '/climb-notes'
    | '/corporate'
    | '/field-guide'
    | '/gnomah'
    | '/login'
    | '/luna'
    | '/method'
    | '/policies'
    | '/privacy'
    | '/procedures'
    | '/service'
    | '/start'
    | '/voice'
    | '/docs/onboarding'
    | '/luna/$slug'
    | '/luna/'
    | '/api/auth/$'
    | '/api/canopy/refresh'
    | '/docs/onboarding/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CanopyRoute: typeof CanopyRoute
  ClimbNotesRoute: typeof ClimbNotesRoute
  CorporateRoute: typeof CorporateRoute
  FieldGuideRoute: typeof FieldGuideRoute
  GnomahRoute: typeof GnomahRoute
  LoginRoute: typeof LoginRoute
  LunaRoute: typeof LunaRouteWithChildren
  MethodRoute: typeof MethodRoute
  PoliciesRoute: typeof PoliciesRoute
  PrivacyRoute: typeof PrivacyRoute
  ProceduresRoute: typeof ProceduresRoute
  ServiceRoute: typeof ServiceRoute
  StartRoute: typeof StartRoute
  VoiceRoute: typeof VoiceRoute
  DocsOnboardingRoute: typeof DocsOnboardingRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCanopyRefreshRoute: typeof ApiCanopyRefreshRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canopy': {
      id: '/canopy'
      path: '/canopy'
      fullPath: '/canopy'
      preLoaderRoute: typeof CanopyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/climb-notes': {
      id: '/climb-notes'
      path: '/climb-notes'
      fullPath: '/climb-notes'
      preLoaderRoute: typeof ClimbNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate': {
      id: '/corporate'
      path: '/corporate'
      fullPath: '/corporate'
      preLoaderRoute: typeof CorporateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/field-guide': {
      id: '/field-guide'
      path: '/field-guide'
      fullPath: '/field-guide'
      preLoaderRoute: typeof FieldGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gnomah': {
      id: '/gnomah'
      path: '/gnomah'
      fullPath: '/gnomah'
      preLoaderRoute: typeof GnomahRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/luna': {
      id: '/luna'
      path: '/luna'
      fullPath: '/luna'
      preLoaderRoute: typeof LunaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/method': {
      id: '/method'
      path: '/method'
      fullPath: '/method'
      preLoaderRoute: typeof MethodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procedures': {
      id: '/procedures'
      path: '/procedures'
      fullPath: '/procedures'
      preLoaderRoute: typeof ProceduresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service': {
      id: '/service'
      path: '/service'
      fullPath: '/service'
      preLoaderRoute: typeof ServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voice': {
      id: '/voice'
      path: '/voice'
      fullPath: '/voice'
      preLoaderRoute: typeof VoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/onboarding': {
      id: '/docs/onboarding'
      path: '/docs/onboarding'
      fullPath: '/docs/onboarding'
      preLoaderRoute: typeof DocsOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/luna/': {
      id: '/luna/'
      path: '/'
      fullPath: '/luna/'
      preLoaderRoute: typeof LunaIndexRouteImport
      parentRoute: typeof LunaRoute
    }
    '/luna/$slug': {
      id: '/luna/$slug'
      path: '/$slug'
      fullPath: '/luna/$slug'
      preLoaderRoute: typeof LunaSlugRouteImport
      parentRoute: typeof LunaRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/canopy/refresh': {
      id: '/api/canopy/refresh'
      path: '/api/canopy/refresh'
      fullPath: '/api/canopy/refresh'
      preLoaderRoute: typeof ApiCanopyRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/onboarding/$': {
      id: '/docs/onboarding/$'
      path: '/$'
      fullPath: '/docs/onboarding/$'
      preLoaderRoute: typeof DocsOnboardingSplatRouteImport
      parentRoute: typeof DocsOnboardingRoute
    }
  }
}

interface LunaRouteChildren {
  LunaSlugRoute: typeof LunaSlugRoute
  LunaIndexRoute: typeof LunaIndexRoute
}

const LunaRouteChildren: LunaRouteChildren = {
  LunaSlugRoute: LunaSlugRoute,
  LunaIndexRoute: LunaIndexRoute,
}

const LunaRouteWithChildren = LunaRoute._addFileChildren(LunaRouteChildren)

interface DocsOnboardingRouteChildren {
  DocsOnboardingSplatRoute: typeof DocsOnboardingSplatRoute
}

const DocsOnboardingRouteChildren: DocsOnboardingRouteChildren = {
  DocsOnboardingSplatRoute: DocsOnboardingSplatRoute,
}

const DocsOnboardingRouteWithChildren = DocsOnboardingRoute._addFileChildren(
  DocsOnboardingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CanopyRoute: CanopyRoute,
  ClimbNotesRoute: ClimbNotesRoute,
  CorporateRoute: CorporateRoute,
  FieldGuideRoute: FieldGuideRoute,
  GnomahRoute: GnomahRoute,
  LoginRoute: LoginRoute,
  LunaRoute: LunaRouteWithChildren,
  MethodRoute: MethodRoute,
  PoliciesRoute: PoliciesRoute,
  PrivacyRoute: PrivacyRoute,
  ProceduresRoute: ProceduresRoute,
  ServiceRoute: ServiceRoute,
  StartRoute: StartRoute,
  VoiceRoute: VoiceRoute,
  DocsOnboardingRoute: DocsOnboardingRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCanopyRefreshRoute: ApiCanopyRefreshRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
