/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CanopyRouteImport } from './routes/canopy'
import { Route as ClimbNotesRouteImport } from './routes/climb-notes'
import { Route as CorporateRouteImport } from './routes/corporate'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProceduresRouteImport } from './routes/procedures'
import { Route as ApiCanopyRefreshRouteImport } from './routes/api/canopy/refresh'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CanopyRoute = CanopyRouteImport.update({
  id: '/canopy',
  path: '/canopy',
  getParentRoute: () => rootRouteImport,
} as any)
const ClimbNotesRoute = ClimbNotesRouteImport.update({
  id: '/climb-notes',
  path: '/climb-notes',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateRoute = CorporateRouteImport.update({
  id: '/corporate',
  path: '/corporate',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProceduresRoute = ProceduresRouteImport.update({
  id: '/procedures',
  path: '/procedures',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCanopyRefreshRoute = ApiCanopyRefreshRouteImport.update({
  id: '/api/canopy/refresh',
  path: '/api/canopy/refresh',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/canopy': typeof CanopyRoute
  '/climb-notes': typeof ClimbNotesRoute
  '/corporate': typeof CorporateRoute
  '/policies': typeof PoliciesRoute
  '/privacy': typeof PrivacyRoute
  '/procedures': typeof ProceduresRoute
  '/api/canopy/refresh': typeof ApiCanopyRefreshRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/canopy': typeof CanopyRoute
  '/climb-notes': typeof ClimbNotesRoute
  '/corporate': typeof CorporateRoute
  '/policies': typeof PoliciesRoute
  '/privacy': typeof PrivacyRoute
  '/procedures': typeof ProceduresRoute
  '/api/canopy/refresh': typeof ApiCanopyRefreshRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/canopy': typeof CanopyRoute
  '/climb-notes': typeof ClimbNotesRoute
  '/corporate': typeof CorporateRoute
  '/policies': typeof PoliciesRoute
  '/privacy': typeof PrivacyRoute
  '/procedures': typeof ProceduresRoute
  '/api/canopy/refresh': typeof ApiCanopyRefreshRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/canopy'
    | '/climb-notes'
    | '/corporate'
    | '/policies'
    | '/privacy'
    | '/procedures'
    | '/api/canopy/refresh'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/canopy'
    | '/climb-notes'
    | '/corporate'
    | '/policies'
    | '/privacy'
    | '/procedures'
    | '/api/canopy/refresh'
  id:
    | '__root__'
    | '/'
    | '/canopy'
    | '/climb-notes'
    | '/corporate'
    | '/policies'
    | '/privacy'
    | '/procedures'
    | '/api/canopy/refresh'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CanopyRoute: typeof CanopyRoute
  ClimbNotesRoute: typeof ClimbNotesRoute
  CorporateRoute: typeof CorporateRoute
  PoliciesRoute: typeof PoliciesRoute
  PrivacyRoute: typeof PrivacyRoute
  ProceduresRoute: typeof ProceduresRoute
  ApiCanopyRefreshRoute: typeof ApiCanopyRefreshRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canopy': {
      id: '/canopy'
      path: '/canopy'
      fullPath: '/canopy'
      preLoaderRoute: typeof CanopyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/climb-notes': {
      id: '/climb-notes'
      path: '/climb-notes'
      fullPath: '/climb-notes'
      preLoaderRoute: typeof ClimbNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate': {
      id: '/corporate'
      path: '/corporate'
      fullPath: '/corporate'
      preLoaderRoute: typeof CorporateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procedures': {
      id: '/procedures'
      path: '/procedures'
      fullPath: '/procedures'
      preLoaderRoute: typeof ProceduresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/canopy/refresh': {
      id: '/api/canopy/refresh'
      path: '/api/canopy/refresh'
      fullPath: '/api/canopy/refresh'
      preLoaderRoute: typeof ApiCanopyRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CanopyRoute: CanopyRoute,
  ClimbNotesRoute: ClimbNotesRoute,
  CorporateRoute: CorporateRoute,
  PoliciesRoute: PoliciesRoute,
  PrivacyRoute: PrivacyRoute,
  ProceduresRoute: ProceduresRoute,
  ApiCanopyRefreshRoute: ApiCanopyRefreshRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
